config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  
  resources :media_items do
    get :load_item_view, on: :collection
  end
end

app/models/image.rb
class Image < ActiveRecord::Base

  belongs_to :media_item

  has_attached_file :file, 
              styles: { medium: "300x300>", thumb: "100x100>" }, 
         default_url: "/images/missing.png"

  validates_attachment :file, presence: true
  validates_attachment :file,
           content_type: { content_type: /\Aimage\/.*\Z/ },
                   size: { less_than: 2.megabytes }

end

app/models/link.rb
class Link < ActiveRecord::Base
  
  belongs_to :media_item
  
  validates_presence_of :link_type
  validates_format_of :url, with: URI::regexp(%w(http https))
  
end

app/models/media_item.rb
class MediaItem < ActiveRecord::Base
  MEDIA_TYPES = %w(image video website)

  belongs_to :user, dependent: :destroy
  has_many :images, dependent: :destroy
  has_one :link, dependent: :destroy
    
  accepts_nested_attributes_for :images, allow_destroy: true
  accepts_nested_attributes_for :link
  
  validates_presence_of :name, :user_id
  validates_inclusion_of :shared, in: [true, false]
  validates_inclusion_of :media_type, in: MediaItem::MEDIA_TYPES
  validates_presence_of :link, if: :is_media_link?
  validates_presence_of :images, if: :is_media_image?
  
  scope :shared, -> { where(shared: true) }
  
  private
    
    def is_media_image?
      media_type == "image"
    end

    def is_media_link?
      !is_media_image?
    end  
      
end

app/models/permitted_params.rb
class PermittedParams

  attr_reader :params

  def initialize(params)
    @params = params
  end
  
  def media_item
    params.require(:media_item).permit(:name, :media_type, :shared, link_attributes: [:url, :link_type], images_attributes: [:file, :_destroy, :id])
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :media_items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  def permitted_params
    @permitted_params ||= PermittedParams.new(params)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @q = MediaItem.shared.ransack(params[:q])
    @items = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(10)
  end

end

app/controllers/media_items_controller.rb
class MediaItemsController < ApplicationController
  before_action :prepare_item, only: [:show, :edit, :update, :destroy]

  def index    
    @q = current_user.media_items.ransack(params[:q])
    @items = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def new
  end
  
  def create
    @item = current_user.media_items.new(permitted_params.media_item)
    if @item.save
      redirect_to media_items_path, notice: 'Media Item successfuly created'
    else
      render :new
    end
  end
  
  def show;end
  
  def edit;end
  
  def load_item_view
    @item = current_user.media_items.new(media_type: params[:type])
    @item.build_link
    @item.images.build 
  end
  
  def update
    if @item.update_attributes(permitted_params.media_item)
      redirect_to media_items_path, notice: 'Media Item successfuly updated'
    else
      render :edit
    end
  end
  
  def destroy
    @item.delete
    redirect_to media_items_path, notice: 'Media Item successfuly removed'
  end

  private
    
    def prepare_item
      @item = current_user.media_items.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def define_item_partial(type)
    %w(image).include?(type) ? 'image' : 'link'
  end
  
  def alert_class_for(type)
    { alert: 'alert-danger', notice: 'alert-success' }[type.to_sym] || type.to_s
  end
  
  def link_to_add_fields(name, f, as)
    new_objects = f.object.send(as).klass.new
    id = new_objects.object_id
    fields = f.fields_for(as, new_objects, child_index: id) do |cf|
      render(as.to_s.singularize + "_fields", f: cf)
    end
    link_to(name, '#', class: 'add_fields', data: { id: id, fields: fields.gsub("\n", "") })
  end
  
end

app/views/home/index.html.slim
h1 Shared Media Items
= render partial: 'shared/search_items', locals: { place: :root }
br
- if @items.any?
  = render partial: 'media_items/items', locals: { items: @items }
- else 
  'No items were shared

app/views/layouts/application.html.slim
doctype html
html
  head
    title AppliftChallenge
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render partial: 'shared/flash'
    = render partial: 'shared/user_nav' unless %w(registrations sessions).include?(controller_name)
    = yield

app/views/media_items/_add_item.html.slim
= simple_form_for @item, multipart: true do |f|
  = f.input :name
  = f.input :media_type, as: :hidden, input_html: { value: @item.media_type }
  = render partial: "edit_#{ define_item_partial(@item.media_type) }", locals: { f: f }
  = f.input :shared
  = f.button :submit
  = link_to 'Cancel', media_items_path

app/views/media_items/_edit_image.html.slim
= f.simple_fields_for :images do |i|
  = render partial: 'image_fields', locals: { f: i }
= link_to_add_fields 'Add Image', f, :images

app/views/media_items/_edit_link.html.slim
= f.simple_fields_for :link do |l|
  = l.input :url, required: true
  = l.input :link_type, as: :hidden, input_html: { value: @item.media_type }, required: true

app/views/media_items/_form.html.slim
= select_tag :media_type, options_for_select(MediaItem::MEDIA_TYPES, @item.try(:media_type)), prompt: "Select media type" unless @item.try(:persisted?)
#media_item
  - if @item.present?
    = render partial: "add_item"

app/views/media_items/_image_fields.html.slim
fieldset
  - if f.object.file.present?
    = image_tag f.object.file(:thumb)
  = f.input :file, as: :file, required: true
  = f.input :_destroy, as: :hidden
  = link_to 'remove', '#', class: 'remove_fields'

app/views/media_items/_items.html.slim
- items.each do |item|
  = render partial: "shared/#{ define_item_partial(item.media_type) }", locals: { item: item }
  - if %w(media_items).include?(controller_name)
    = link_to 'Edit item', edit_media_item_path(item)
    = " | "
    = link_to 'Remove item', media_item_path(item), method: :delete
= paginate items

app/views/media_items/edit.html.slim
h1 Edit Media Item
= render partial: 'form'

app/views/media_items/index.html.slim
h1 Manage Your Media Items
= link_to 'Add New Media Item', new_media_item_path
br
br
= render partial: 'shared/search_items', locals: { place: :media_items }
- if @items.any?
  = render partial: 'items', locals: { items: @items }
- else
  br
  'You have no items

app/views/media_items/load_item_view.js.slim
- if @item.media_type.present?
  '$('#media_item').html('#{ escape_javascript(render partial: "add_item") }');
- else
  '$('#media_item').empty()

app/views/media_items/new.html.slim
h1 Add Media Item
= render partial: 'form'

app/views/shared/_flash.html.slim
- flash.each do |type, message|
  div class="alert #{ alert_class_for(type) } alert-dismissible fade in"
    button type="button" class="close" data-dismiss="alert"
      span aria-hidden="true" &times
    = message

app/views/shared/_image.html.slim
h2 = item.name
- item.images.each do |img|
  = image_tag img.file(:medium)

app/views/shared/_link.html.slim
h2 = item.name
p = item.link.url

app/views/shared/_search_items.html.slim
= search_form_for @q, url: send("#{ place.to_s }_path") do |f|
  = f.search_field :name_cont
  = f.select :media_type_eq, options_for_select(MediaItem::MEDIA_TYPES, params[:q].try(:[], :media_type_eq)), include_blank: "Select media type"
  = f.submit

app/views/shared/_user_nav.html.slim
- if current_user
  h2 
    = "#{ current_user.email } | "
    = link_to 'Home', root_path
    = ' | '
    = link_to 'Manage Media Items', media_items_path
    = ' | '
    = link_to 'Logout', destroy_user_session_path
- else
  h2
    = link_to 'Sign in', new_user_session_path
    = ' | '
    = link_to 'Sign up', new_user_registration_path